name: ChunkRateLimit
main: org.inventivetalent.chunkratelimit.ChunkRateLimitPlugin
author: inventivetalent
version: ${project.version}

depend: [ProtocolLib]

permissions:
  chunkratelimit.bypass:
    description: "Bypass the chunk rate limit"
    default: false